In [1]:
import numpy as np 

arr_4x4 = np.random.exponential(scale=1.0, size=(4, 4))
print(arr_4x4)


[[1.75029719 1.45953493 0.1117559  0.24471155]
 [1.26722801 0.82006851 1.83419729 0.02546338]
 [0.44351018 0.1469432  2.0826129  2.07673233]
 [0.33820332 1.82982652 0.70154037 0.17038325]]
